services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./volumes/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yaml:ro
      - ./volumes/prometheus/data:/prometheus
    restart: unless-stopped